baseURL = "https://uncopied.github.io/blog"
languageCode = "en-us"
title = "UNCOPIED blog"
theme = "ananke"
publishdir = "docs"
enableRobotsTXT = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number


[languages]
  [languages.en]
    title = "UNCOPIED, a blog for uncopiers"
    weight = 1
    contentDir = "content/en"
	languageCode = "en-us"
  [languages.fr]
    title = "UNCOPIED, le blogue des décopieurs"
    weight = 2
    contentDir = "content/fr"
	languageCode = "fr-FR"
	
[params]
  favicon = ""
  site_logo = ""
  description = "UNCOPIED certificates of authenticity, expertise or inventory for original art works : stories, making-of and use cases."
  facebook = ""
  twitter = "https://twitter.com/uncopied_art"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5